# Generated by Django 4.0.2 on 2022-05-04 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_jenis_products_kelompok'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelompok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelompok', models.CharField(max_length=30, null=True, verbose_name=(('1', 'Hobi'), ('2', 'Elektronik'), ('3', 'Home Tools'), ('4', 'Fashion')))),
                ('nama_perent', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='jenis_products',
            name='kelompok',
        ),
        migrations.AddField(
            model_name='jenis_products',
            name='kel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kel_fk', to='products.kelompok'),
        ),
    ]
