# Generated by Django 4.0.2 on 2022-05-04 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0003_kelompok_remove_jenis_products_kelompok_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelompok',
            name='kelompok',
            field=models.CharField(choices=[('1', 'Hobi'), ('2', 'Elektronik'), ('3', 'Home Tools'), ('4', 'Fashion')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.CharField(max_length=200)),
                ('harga_jual', models.IntegerField()),
                ('harga_beli', models.IntegerField()),
                ('qt', models.IntegerField()),
                ('sku', models.CharField(max_length=20)),
                ('mu', models.DateField(auto_now=True)),
                ('cu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cu_fk_prod', to=settings.AUTH_USER_MODEL)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prod_fk', to='products.jenis_products')),
            ],
            options={
                'db_table': 'Products',
            },
        ),
    ]
