# Generated by Django 4.0.2 on 2022-05-04 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_alter_kelompok_kelompok_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'XL'), ('2', 'XXL'), ('3', 'L'), ('4', 'M'), ('5', 'S')], max_length=50),
        ),
        migrations.AddField(
            model_name='products',
            name='warna',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Merah'), ('2', 'Kuning'), ('3', 'Hijau'), ('4', 'Biru'), ('5', 'Kuning'), ('6', 'Abu-Abu'), ('7', 'Putih'), ('8', 'Gold'), ('9', 'Hitam')], max_length=50),
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=10)),
                ('mu', models.DateField(auto_now=True)),
                ('cu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='merk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merk_fk', to='products.brand'),
        ),
    ]
